name: Inspection

# Run this pipeline whenver a PR is raised to master
on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the codebase
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v3

    # Install Node Version
    - name: Install NodeJS â¬‡ï¸
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    # Install dependencies
    - name: Install Dependencies ğŸšš
      run: npm ci

    # Create a build
    - name: Build ğŸ”§
      run: npm run build --if-present
